### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by flemton** [ashmalzahra/Bugs-hide-and-seek#1]
#### Below were the bugs I found
 in [popup.js](https://github.com/ashmalzahra/bug-repo/blob/main/popup.js), on: 

- line 159 to 177, the entire code block was commented out
- line 128 to 130 and 141 to 143, technologies were not indexed
- line 30, id had no value nor comma
Those were the only issues I found, cheers 🥂

**Comment by ashmalzahra** [comment]
**Congratulations** @flemton 👏
Great job identifying the bugs! ✔️
